apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "cloudgitops.io"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: "james.knott@ghettolabs.io"
      enabled: true
      production: true
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
