apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jenkins-pipeline
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "218395976652"
    project: jenkins-terraform-309606
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: james-knott
    repository: gkecluster
  - key: staging
  - key: production
  ingress:
    domain: dev.cloudgitops.io
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: james.knott@ghettolabs.io
      enabled: true
      production: true
  kuberhealthy: true
  pipelineUser:
    username: ghettolabs-bot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-jenkins-pipeline-a9ce7b13e874
  - name: reports
    url: gs://reports-jenkins-pipeline-a9ce7b13e874
  - name: repository
    url: gs://repository-jenkins-pipeline-a9ce7b13e874
  vault: {}
  webhook: lighthouse
